<a href="https://colab.research.google.com/github/Jumper15/pytorch-work/blob/main/SLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.functional as F

# string = open("names.txt", "r").read(100)
string = """
emma
olivia
ava
isabella
sophia
charlotte
mia
amelia
harper
evelyn
abigail
emily
elizabeth
mila
ella
avery
sofia
camila
aria
scarlett
victoria
madison
luna
grace
chloe
penelope
layla
riley
zoey
nora
lily
eleanor
hannah
lillian
addison
aubrey
ellie
stella
natalie
zoe
leah
hazel
violet
aurora
savannah
audrey
brooklyn
bella
claire
skylar
lucy
paisley
everly
anna
caroline
nova
genesis
emilia
kennedy
samantha
maya
willow
kinsley
naomi
aaliyah
elena
sarah
ariana
allison
gabriella
alice
madelyn
cora
ruby
eva
serenity
autumn
adeline
hailey
gianna
valentina
isla
eliana
quinn
nevaeh
ivy
sadie
piper
lydia
alexa
josephine
emery
julia
delilah
arianna
vivian
kaylee
sophie
brielle
madeline
peyton
rylee
clara
hadley
melanie
mackenzie
reagan
adalynn
liliana
aubree
jade
katherine
isabelle
natalia
raelynn
maria
athena
ximena
arya
leilani
taylor
faith
rose
kylie
alexandra
mary
margaret
lyla
ashley
amaya
eliza
brianna
bailey
andrea
khloe
jasmine
melody
iris
isabel
norah
annabelle
valeria
emerson
adalyn
ryleigh
eden
emersyn
anastasia
kayla
alyssa
juliana
charlie
esther
ariel
cecilia
valerie
alina
molly
reese
aliyah
lilly
parker
finley
morgan
sydney
jordyn
eloise
trinity
daisy
kimberly
lauren
genevieve
sara
arabella
harmony
elise
remi
teagan
alexis
london
sloane
laila
lucia
diana
juliette
sienna
elliana
londyn
ayla
callie
gracie
josie
amara
jocelyn
daniela
everleigh
mya
rachel
summer
alana
brooke
alaina
mckenzie
catherine
amy
presley
journee
rosalie
ember
brynlee
rowan
joanna
paige
rebecca
ana
sawyer
mariah
nicole
brooklynn
payton
marley
fiona
georgia
lila
harley
adelyn
alivia
noelle
gemma
vanessa
journey
makayla
angelina
adaline
catalina
alayna
julianna
leila
lola
adriana
june
juliet
jayla
river
tessa
lia
dakota
delaney
selena
blakely
ada
camille
zara
malia
hope
samara
vera
mckenna
briella
izabella
hayden
raegan
michelle
angela
ruth
freya
kamila
vivienne
aspen
olive
kendall
elaina
thea
kali
destiny
amiyah
evangeline
cali
blake
elsie
juniper
alexandria
myla
ariella
kate
mariana
lilah
charlee
daleyza
nyla
jane
maggie
zuri
aniyah
lucille
leia
melissa
adelaide
amina
giselle
lena
camilla
miriam
millie
brynn
gabrielle
sage
annie
logan
lilliana
haven
jessica
kaia
magnolia
amira
adelynn
makenzie
stephanie
nina
phoebe
arielle
evie
lyric
alessandra
gabriela
paislee
raelyn
madilyn
paris
makenna
kinley
gracelyn
talia
maeve
rylie
kiara
evelynn
brinley
jacqueline
laura
gracelynn
lexi
ariah
fatima
jennifer
kehlani
alani
ariyah
luciana
allie
heidi
maci
phoenix
felicity
joy
kenzie
veronica
margot
addilyn
lana
cassidy
remington
saylor
ryan
keira
harlow
miranda
angel
amanda
daniella
royalty
gwendolyn
ophelia
heaven
jordan
madeleine
esmeralda
kira
miracle
elle
amari
danielle
daphne
willa
haley
gia
kaitlyn
oakley
kailani
winter
alicia
serena
nadia
aviana
demi
jada
braelynn
dylan
ainsley
alison
camryn
avianna
bianca
skyler
scarlet
maddison
nylah
sarai
regina
dahlia
nayeli
raven
helen
adrianna
averie
skye
kelsey
tatum
kensley
maliyah
erin
viviana
jenna
anaya
carolina
shelby
sabrina
mikayla
annalise
octavia
lennon
blair
carmen
yaretzi
kennedi
mabel
zariah
kyla
christina
selah
celeste
eve
mckinley
milani
frances
jimena
kylee
leighton
katie
aitana
kayleigh
sierra
kathryn
rosemary
jolene
alondra
elisa
helena
charleigh
hallie
lainey
avah
jazlyn
 """

Create SLP
- parse words into token arrays => xs, ys
- one hot encode xs into (n, 27) matrix
- create randomized weights as hidden/output layer (27, 27)
- perform matrix mult on input and output matrix
- calculate loss through average negative log value

In [ ]:
# encode/decode functions

chrs = sorted(list(set(string)))

stoi = {chr: i for i, chr in enumerate(chrs[2:])}
stoi["."] = 26
itos = {i: chr for chr, i in stoi.items()}

def encode(str):
  return [stoi[chr] for chr in str]

def decode(nums):
  return [itos[int(num)] for num in str(nums)]



In [ ]:
# seperate words into token arrays

import torch.nn.functional as F

words = string.splitlines()
words = words[1: 10]
# for word in words:
word = ["."] + list(words[2]) + ["."]

xs = encode(word)
xs = torch.tensor(xs)
xs_e = F.one_hot(xs).type(torch.float16)

ys = xs

xs_e, ys

(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=torch.float16),
 tensor([26,  0, 21,  0, 26]))

In [ ]:
# create hidden layer

slp = torch.rand((27, 27), dtype=torch.float16, requires_grad=True)

# perform matrix mult
output = xs_e @ slp

xs_e[0], slp, output[0]

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=torch.float16),
 tensor([[0.4277, 0.6401, 0.7134, 0.3315, 0.7036, 0.3335, 0.5610, 0.7939, 0.6934,
          0.8457, 0.1108, 0.5020, 0.5864, 0.5820, 0.5142, 0.2520, 0.2510, 0.5693,
          0.3535, 0.7471, 0.1143, 0.6890, 0.0366, 0.1870, 0.5361, 0.8984, 0.9287],
         [0.1987, 0.6509, 0.6206, 0.7114, 0.4321, 0.9814, 0.1099, 0.5142, 0.8813,
          0.8472, 0.4688, 0.5405, 0.6714, 0.3169, 0.7241, 0.2090, 0.1191, 0.5083,
          0.5098, 0.6045, 0.4326, 0.4980, 0.7095, 0.7520, 0.1538, 0.1382, 0.7720],
         [0.9541, 0.3423, 0.5513, 0.6499, 0.9565, 0.1265, 0.3657, 0.2471, 0.4419,
          0.4639, 0.1841, 0.8120, 0.6846, 0.5498, 0.6343, 0.3931, 0.6855, 0.3594,
          0.7700, 0.4111, 0.1235, 0.3818, 0.5752, 0.6084, 0.9136, 0.5591, 0.6328],
         [0.1104, 0.7925, 0.9204, 0.1479, 0.1191, 0.5498, 0.0698, 0.6968, 0.7085,
          0.9229, 0.9546, 0.

In [ ]:
# combining

words = string.splitlines()
words = words[1: 9]

for word in words:
  word = ["."] + list(word) + ["."]
  xs = encode(word)
  xs = torch.tensor(xs)
  xs_e = F.one_hot(xs).type(torch.float16)
  xs_e = xs_e[:-1]
  ys = xs[1:]
  # print(f"{word}:\n\n xs - {xs},\n\n xs_e - {xs_e},\n\n ys - {ys}\n\n")

  # matrix mult
  output = xs_e @ slp
  output /= torch.sum(output, 1, keepdims=True)
  # print(output)
  loss = 0
  loss_count = 0
  for y in range(len(ys)):
    loss += -torch.log(output[y][ys[y]])
    loss_count += 1
    # print(output[y][ys[y]], loss)
  print(loss / loss_count)

  # backprop
  slp.grad = None
  loss.backward()
  slp.data += -0.1 * slp.grad

tensor(3.2402, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(3.1387, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(3.1426, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(3.2715, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(2.9688, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(3.4316, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(2.9824, dtype=torch.float16, grad_fn=<DivBackward0>)
tensor(2.8008, dtype=torch.float16, grad_fn=<DivBackward0>)
